version: '3'
services:
  serve-discover:
    build: ./serve-discover
    restart: always
    container_name: razor-serve-discover
    ports:
      - '35001:35001'

  serve-oauth2:
    build: ./serve-oauth2
    restart: always
    container_name: razor-serve-oauth2
    ports:
      - '9001:9001'
    depends_on:
      - serve-discover

  serve-gateway:
    build: ./serve-gateway
    restart: always
    container_name: razor-serve-gateway
    ports:
      - '80:80'
    depends_on:
      - serve-discover