version: '3'
services:
  serve-discover:
    build: ./serve-discover
    restart: always
    container_name: razor-serve-discover
    networks:
      - razor-net
    ports:
      - '35001:35001'

  serve-config:
    build: ./serve-config
    restart: always
    container_name: razor-serve-config
    networks:
      - razor-net
    expose:
      - 35002
    depends_on:
      - serve-discover

  serve-oauth2:
    build: ./serve-oauth2
    restart: always
    container_name: razor-serve-oauth2
    networks:
      - razor-net
    expose:
      - 9001
    depends_on:
      - serve-config

  business-order:
    build: ./business-order
    restart: always
    container_name: razor-business-order
    networks:
      - razor-net
    expose:
      - 8002
    depends_on:
      - serve-config

  business-payment:
    build: ./business-payment
    restart: always
    container_name: razor-business-payment
    networks:
      - razor-net
    expose:
      - 8001
    depends_on:
      - serve-config

  serve-gateway:
    build: ./serve-gateway
    restart: always
    container_name: razor-serve-gateway
    networks:
      - razor-net
    ports:
      - '80:80'
    depends_on:
      - serve-config

networks:
  razor-net: