server:
  port: 35001

eureka:
  instance:
    hostname: SERVE-DISCOVER
  client:
    register-with-eureka: false # 不向注册中心注册自己
    fetch-registry: false # 注册中心不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 服务地址