server:
  port: 80

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true               # 开启从注册中心动态创建路由的功能
      routes:
        - id: business-payment         # 路由的id, 要求唯一
          uri: lb://business-payment   # 服务地址
          predicates:
            - Path=/payment/**         # 断言,路径匹配进行路由

        - id: business-order
          uri: lb://business-order
          predicates:
            - Path=/order/**

        - id: serve-oauth2            # 授权服务
          uri: lb://serve-oauth2
          predicates:
            - Path=/oauth/**

eureka:
  instance:
    hostname: serve-gateway
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://serve-discover:35001/eureka