server:
  port: 9001

spring:
  application:
    name: oauth2-serve
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver # driver-class-name: com.mysql.cj.jdbc.Driver # MySql8.x
      url: jdbc:mysql://mysql-server:3306/develop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
  main:
    allow-bean-definition-overriding: true



# 服务注册
eureka:
  client:
    service-url:
      defaultZone: http://serve-discover:35001/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yangb.api.common.entities.serve.oauth2