server:
  port: 35002

spring:
  application:
    name: gateway-serve
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true               # 开启从注册中心动态创建路由的功能
      routes:
        - id: payment-service         # 路由的id, 要求唯一
          uri: lb://PAYMENT-SERVICE   # 服务地址
          predicates:
            - Path=/payment/**        # 断言,路径匹配进行路由

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**

        - id: oauth2-serve            # 授权服务
          uri: lb://OAUTH2-SERVE
          predicates:
            - Path=/oauth/**

eureka:
  instance:
    hostname: gateway-serve
  client:
    service-url:
      defaultZone: http://localhost:35001/eureka