server:
  port: 8002

spring:
  application:
    name: order-service
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/quick_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true

# 服务注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:35001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

# feign 连接超时配置
ribbon:
    ReadTimeout: 5000 # 连接建立后响应时间
    ConnectTimeout: 5000 # 建立连接所用的时间

logging:
  level:
    com.yangb.business.order.service.PaymentFeignService: debug # feign日志以什么级别监控哪个接口